import os
from dotenv import load_dotenv

load_dotenv()


GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

GEMINI_MODEL = os.getenv(
    "GEMINI_MODEL",
    "gemini-2.5-flash"
)

MAX_IMAGE_SIZE_MB = int(
    os.getenv("MAX_IMAGE_SIZE_MB", "10")
)

VISION_CATEGORY_CONFIDENCE_THRESHOLD = float(
    os.getenv("VISION_CATEGORY_CONFIDENCE_THRESHOLD", "0.75")
)

VISION_SEVERITY_CONFIDENCE_THRESHOLD = float(
    os.getenv("VISION_SEVERITY_CONFIDENCE_THRESHOLD", "0.75")
)

# --- Added for geo module ---
NOMINATIM_USER_AGENT = os.getenv(
    "NOMINATIM_USER_AGENT",
    "CIVIC_AI_NLP_INTEGRATED/0.1.0 (contact: singhmohit1729@gmail.com)"
)


class Settings:
    GEMINI_API_KEY = GEMINI_API_KEY
    GEMINI_MODEL = GEMINI_MODEL
    MAX_IMAGE_SIZE_MB = MAX_IMAGE_SIZE_MB
    VISION_CATEGORY_CONFIDENCE_THRESHOLD = VISION_CATEGORY_CONFIDENCE_THRESHOLD
    VISION_SEVERITY_CONFIDENCE_THRESHOLD = VISION_SEVERITY_CONFIDENCE_THRESHOLD
    NOMINATIM_USER_AGENT = NOMINATIM_USER_AGENT

settings = Settings()
