import os
from dotenv import load_dotenv

load_dotenv()


GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

GEMINI_MODEL = os.getenv(
    "GEMINI_MODEL",
    "gemini-2.5-flash"
)

MAX_IMAGE_SIZE_MB = int(
    os.getenv("MAX_IMAGE_SIZE_MB", "10")
)

VISION_CATEGORY_CONFIDENCE_THRESHOLD = float(
    os.getenv("VISION_CATEGORY_CONFIDENCE_THRESHOLD", "0.75")
)

VISION_SEVERITY_CONFIDENCE_THRESHOLD = float(
    os.getenv("VISION_SEVERITY_CONFIDENCE_THRESHOLD", "0.75")
)

# --- Added for geo module ---
NOMINATIM_USER_AGENT = os.getenv(
    "NOMINATIM_USER_AGENT",
    "CIVIC_AI_NLP_INTEGRATED/0.1.0 (contact: singhmohit1729@gmail.com)"
)

EMBEDDING_PROVIDER = os.getenv("EMBEDDING_PROVIDER", "tfidf")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "TfidfVectorizer(char_wb)")
EMBEDDING_VERSION = os.getenv("EMBEDDING_VERSION", "1")
DUPLICATE_TOP_K = int(os.getenv("DUPLICATE_TOP_K", "10"))
DUPLICATE_SCORE_THRESHOLD = float(os.getenv("DUPLICATE_SCORE_THRESHOLD", "0.82"))
POSSIBLE_DUPLICATE_SCORE_THRESHOLD = float(os.getenv("POSSIBLE_DUPLICATE_SCORE_THRESHOLD", "0.62"))
SEMANTIC_WEIGHT = float(os.getenv("SEMANTIC_WEIGHT", "0.45"))
LEXICAL_WEIGHT = float(os.getenv("LEXICAL_WEIGHT", "0.10"))
CATEGORY_WEIGHT = float(os.getenv("CATEGORY_WEIGHT", "0.10"))
ISSUE_WEIGHT = float(os.getenv("ISSUE_WEIGHT", "0.20"))
GEO_WEIGHT = float(os.getenv("GEO_WEIGHT", "0.15"))
TEMPORAL_WEIGHT = float(os.getenv("TEMPORAL_WEIGHT", "0.05"))
VISUAL_WEIGHT = float(os.getenv("VISUAL_WEIGHT", "0.05"))
DUPLICATE_GEO_RADIUS_METERS = float(os.getenv("DUPLICATE_GEO_RADIUS_METERS", "250.0"))


class Settings:
    GEMINI_API_KEY = GEMINI_API_KEY
    GEMINI_MODEL = GEMINI_MODEL
    MAX_IMAGE_SIZE_MB = MAX_IMAGE_SIZE_MB
    VISION_CATEGORY_CONFIDENCE_THRESHOLD = VISION_CATEGORY_CONFIDENCE_THRESHOLD
    VISION_SEVERITY_CONFIDENCE_THRESHOLD = VISION_SEVERITY_CONFIDENCE_THRESHOLD
    NOMINATIM_USER_AGENT = NOMINATIM_USER_AGENT
    EMBEDDING_PROVIDER = EMBEDDING_PROVIDER
    EMBEDDING_MODEL = EMBEDDING_MODEL
    EMBEDDING_VERSION = EMBEDDING_VERSION
    DUPLICATE_TOP_K = DUPLICATE_TOP_K
    DUPLICATE_SCORE_THRESHOLD = DUPLICATE_SCORE_THRESHOLD
    POSSIBLE_DUPLICATE_SCORE_THRESHOLD = POSSIBLE_DUPLICATE_SCORE_THRESHOLD
    SEMANTIC_WEIGHT = SEMANTIC_WEIGHT
    LEXICAL_WEIGHT = LEXICAL_WEIGHT
    CATEGORY_WEIGHT = CATEGORY_WEIGHT
    ISSUE_WEIGHT = ISSUE_WEIGHT
    GEO_WEIGHT = GEO_WEIGHT
    TEMPORAL_WEIGHT = TEMPORAL_WEIGHT
    VISUAL_WEIGHT = VISUAL_WEIGHT
    DUPLICATE_GEO_RADIUS_METERS = DUPLICATE_GEO_RADIUS_METERS

settings = Settings()
